### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by DavidWells** [brielov/typed#1]
Very cool library. Kudos on making it super fast + tiny ❤️

Had a question about the API. 

Instead of returning the object, have you considered returning a tuple?

```diff
import * as T from "typed";

const postType = T.object({
  id: T.number,
  title: T.string,
  tags: T.array(T.string),
});

-const result = postType(/* some JSON data */);
+const [ errors, value ] = postType(/* some JSON data */);

if (errors) {
  // errors is available inside this other block
  throw new Error(errors);
} 

// Valid value
console.log(value)
```

It seems like `result.success` and `result.value` return the same signal of the type-checking working.

If it were a tuple it would perhaps make it easier to reference/name the value or errors returned, e.g.

```js
const [ postErrors, post ] = postType(/* some JSON data */);
const [ otherErrors, otherThing ] = otherType(/* some JSON data */);
```

Anywho, just a thought I had while checking this out. Again great work 😃

Aside: It would be cool to generate these from types like https://github.com/fabien0102/ts-to-zod too

**Comment by brielov** [comment]
Hi there! Thanks for the kind words. I honestly didn't think about returning a tuple while developing `typed`. I understand your point and it is a valid one. I guess it is a matter of taste / convenience, so if people really start using `typed` more aggressively I'd consider putting this out to a vote and based on what the majority feels, maybe do a refactor and release a major version. Does that sounds fare? About the `ts-to-zod` repo, I didn't know that even existed until now. Seems pretty cool! I don't know if I have the brains to pull that off but maybe with a little help from contributors we can actually make it happen.
