### ISSUE TITLE
Typescript is not inferring Err properly on 4.0.0

### ISSUE THREAD

**Issue by renatorib** [brielov/typed#33]
Repro:
https://stackblitz.com/edit/typescript-vhd1gg?file=index.ts

Demonstration:
![image](https://user-images.githubusercontent.com/3277185/165373384-e1daa7ad-4c14-482c-b77d-183b132985a3.png)

(btw, I should open another issue for that but just in case... `foo` should not be inferred as `string | null` as it is nullable?)

**Comment by renatorib** [comment]
Hmm it works if we explicitly check ok as true
![image](https://user-images.githubusercontent.com/3277185/165379166-b0866290-c379-4047-af23-eaabcb3c3282.png)

It's weird since in the if branch it understand the union t.Ok, but else branch doesn't. 
And of course not very ergonomic

**Comment by brielov** [comment]
Hi there! Just curious, is your tsconfig set as strict?

**Comment by renatorib** [comment]
Oh. Nevermind

I use strict true in my projects but just wanted to try typed@4 in a stackblitz and I completely forgot that it comes with strict false by default...

**Comment by brielov** [comment]
Hahah no worries! It happens to me also. Thanks for reaching out though!
